### ISSUE TITLE
how to run this on windows machine

### ISSUE THREAD

**Issue by sk-diagnal** [JungWinter/split#16]
how to run this on windows machine .. I have to split my tags but on windows machine . How to use jungwinter /split for that

**Comment by winterjung** [comment]
@sk-diagnal I didn't test yet it on windows machine or cr-lf base multi line case. I'll test and remain how to run actions. thanks.

**Comment by winterjung** [comment]
When I [tested on windows-2022](https://github.com/JungWinter/split/actions/runs/4401195122/jobs/7707170911), I got the error because container action is only supported on Linux.

To solve this problem, I need to change docker container-based actions to javascript-based actions, but I don't plan to do that for the time being, so I'll close this issue.
